api_platform:
    title: HomeBalance Task & Score API
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/ApiResource'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
