root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: portal_dashboard

controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
